Feature/cc 256 cc dep v2
WebDevStudios/constant-contact-forms pull request #556
Opened 2021-07-26 17:28 UTC by Oceas

Updated all reported dependencies that can be.

Ticket: https://webdevstudios.atlassian.net/browse/CC-256

2021-08-02 20:38 UTC, richaber requested changes

2021-08-02 20:38 UTC, richaber commented on package.json
> +    "sass": "^1.36.0"
I don't think these should be production `dependencies`, I believe they should be `devDependencies`.

```
npm install postcss --save-dev
npm install sass --save-dev
```

2021-08-18 17:44 UTC, Oceas commented on package.json
> +    "sass": "^1.36.0"
Updated ready for rereview.

2021-09-09 23:53 UTC, richaber approved these changes

2021-09-09 23:53 UTC, merged