Renamed nonce typo and added nonce verification.
WebDevStudios/constant-contact-forms pull request #562
Opened 2021-08-10 18:15 UTC by Oceas

Ticket: https://webdevstudios.atlassian.net/browse/CC-260

Description: Resolves typo in nonce_url and adds nonce verification where it previously didn't exist.

2021-08-17 18:23 UTC, richaber requested changes
It should not return when the nonce _is_ valid.

![Screen Shot 2021-08-17 at 1 21 32 PM](https://user-images.githubusercontent.com/5407441/129779997-4c1089bf-a467-4ee8-96f9-86a67f7cb942.png)

2021-08-17 18:23 UTC, richaber commented on includes/class-lists.php
> +		if ( ! isset( $ctct_resyncing ) || wp_verify_nonce( $ctct_resyncing, 'ctct_resyncing' ) || ! is_admin() ) {
@Oceas There's an error in this logic.

2021-08-19 13:36 UTC, Oceas commented on includes/class-lists.php
> +		if ( ! isset( $ctct_resyncing ) || wp_verify_nonce( $ctct_resyncing, 'ctct_resyncing' ) || ! is_admin() ) {
Please find changes made. I believe laps may have been in last minute cleanups. Fresh testing and syncing works.

2021-09-10 15:17 UTC, richaber approved these changes
Looks good. Tested with xdebug and got the result I expected.

2021-09-10 15:17 UTC, merged