Update social icons in plugin list
WebDevStudios/constant-contact-forms pull request #678
Opened 2024-07-22 14:16 UTC by tw2113

This PR removes Google+ which no longer exists, and removes Twitter which is not functioning like it used to. Probably due to platform changes. I tried the same URL with x.com and it didn't fix anything.

2024-08-29 21:14 UTC, ramsesdelr commented on includes/class-admin.php
> -		$add_links[]  = '<a title="' . $social_share . '" href="https://twitter.com/home?status=' . $twitter_cta . ' ' . $site_link . '" target="_blank" rel="noopener noreferrer" class="dashicons-before da
I think you can replace this URL with: `https://twitter.com/intent/tweet?text=`, can you give it a try please?

2024-08-29 21:14 UTC, ramsesdelr requested changes
I left a comment regarding the twitter share link.

2024-08-29 23:49 UTC, tw2113 commented on includes/class-admin.php
> -		$add_links[]  = '<a title="' . $social_share . '" href="https://twitter.com/home?status=' . $twitter_cta . ' ' . $site_link . '" target="_blank" rel="noopener noreferrer" class="dashicons-before da
Almost, looks like it'll want to be `https://x.com/intent/post?text=` due to tragic loss of branding

2024-08-29 23:51 UTC, tw2113 commented on includes/class-admin.php
> -		$add_links[]  = '<a title="' . $social_share . '" href="https://twitter.com/home?status=' . $twitter_cta . ' ' . $site_link . '" target="_blank" rel="noopener noreferrer" class="dashicons-before da
the CTA is already escaped via `esc_html__()`, but I can do so for the sitelink.

2024-08-30 00:09 UTC, tw2113 commented on includes/class-admin.php
> -		$add_links[]  = '<a title="' . $social_share . '" href="https://twitter.com/home?status=' . $twitter_cta . ' ' . $site_link . '" target="_blank" rel="noopener noreferrer" class="dashicons-before da
This should all be resolved with https://github.com/WebDevStudios/constant-contact-forms/pull/678/commits/50c490273437a4f5bb3c731897fd24bec11213ad

2024-08-30 14:02 UTC, ramsesdelr approved these changes
Approved!

2024-08-30 14:38 UTC, merged