remove reliance on meta data and instead rely on POST data for lists being used.
WebDevStudios/constant-contact-forms pull request #680
Opened 2024-08-12 20:59 UTC by tw2113

The metadata now stores ALL of the chosen lists as meta, and not just items checked by the user.

2024-08-29 20:56 UTC, ramsesdelr commented on includes/class-mail.php
> +		if ( ! empty( $_POST ) && is_array( $_POST ) ) {
Can we add a `//phpcs:ignore` to this line and the one below to avoid the nonce  warning from PHPCS?

2024-08-29 20:57 UTC, ramsesdelr requested changes
Added a quick change, can you please take a look @tw2113 ?

2024-08-30 00:11 UTC, tw2113 commented on includes/class-mail.php
> +		if ( ! empty( $_POST ) && is_array( $_POST ) ) {
This should be resolved in 935d431b

2024-08-30 13:37 UTC, ramsesdelr approved these changes
Looks good, approved, thanks!

2024-08-30 14:37 UTC, merged